import { gameState } from "../engine/gameState.js";
import { renderHeaderHud } from "../components/HeaderHud.js";
const nf=n=>Number(n||0).toLocaleString("es-AR");
export function renderMonetizacion(el){
 const c=el||document.getElementById("monetizacionScreen"); if(!c)return; const p=gameState.player; p.monetizacion ||= {acuerdos:[],campaniasActivas:[],historial:[]};
 const ofertas=gameState.monetizacionCatalogo(); const activas=p.monetizacion.campaniasActivas||[]; const hist=p.monetizacion.historial||[];
 c.innerHTML=`<div class="page-shell monetizacion-page">${renderHeaderHud()}
 <div class="dashboard-top"><div><div class="eyebrow">💰 MONETIZACIÓN</div><h1 class="page-title">Convertí audiencia en ingresos.</h1><p class="page-subtitle">No todas las marcas pagan lo mismo: los acuerdos dependen de tu tamaño, alcance y formato.</p></div><a href="#dashboard" class="btn ghost">← Volver</a></div>
 <section class="monetization-overview"><div><small>INGRESOS PUBLICITARIOS</small><b>$${nf(p.ingresosDesglose?.publicidad)}</b></div><div><small>ACUERDOS DE MARCA</small><b>$${nf(p.ingresosDesglose?.sponsors)}</b></div><div><small>CAMPAÑAS ACTIVAS</small><b>${activas.length}/2</b></div><div><small>VISTAS DEL TRIMESTRE</small><b>${nf(p.actividadTrimestre?.vistas||0)}</b></div></section>
 <section class="panel"><div class="store-section-head"><div><span class="eyebrow">OPORTUNIDADES</span><h2>Acuerdos disponibles</h2></div><span class="store-meta">Pago según rendimiento real</span></div><div class="campaign-grid">${ofertas.length?ofertas.map(o=>`<article class="campaign-card"><div class="campaign-top"><span>${o.tipo}</span><strong>${o.marca}</strong></div><h3>${o.descripcion}</h3><div class="campaign-stats"><div><small>Pago por 1.000 vistas</small><b>$${nf(o.pagoPorMil)}</b></div><div><small>Objetivo orientativo</small><b>${nf(o.objetivo)} vistas</b></div><div><small>Tope del acuerdo</small><b>$${nf(o.maxPago)}</b></div></div><button class="btn primary campaign-sign" data-id="${o.id}" ${activas.length>=2||activas.some(x=>x.id===o.id)?"disabled":""}>${activas.some(x=>x.id===o.id)?"YA FIRMADO":activas.length>=2?"2 CAMPAÑAS ACTIVAS":"FIRMAR ACUERDO"}</button></article>`).join(""):`<div class="store-empty">Todavía no tenés campañas disponibles. Seguí creciendo para desbloquear acuerdos mejores.</div>`}</div></section>
 <section class="panel"><div class="store-section-head"><div><span class="eyebrow">ACTIVAS</span><h2>Campañas en curso</h2></div></div>${activas.length?`<div class="campaign-active-list">${activas.map(a=>`<div class="campaign-active"><div><b>${a.marca}</b><span>${a.tipo} · ${nf(Math.max(0,(p.vistasTotales||0)-(a.vistasInicio||0)))} vistas acumuladas</span></div><strong>$${nf(a.pagoPorMil)}/1K</strong></div>`).join("")}</div>`:`<p class="muted">No tenés campañas activas. Cuando firmes una, el pago se calculará al cerrar el trimestre según las visitas reales.</p>`}</section>
 <section class="panel"><div class="store-section-head"><div><span class="eyebrow">HISTORIAL</span><h2>Acuerdos liquidados</h2></div></div>${hist.length?`<div class="mini-list">${hist.slice(-12).reverse().map(a=>`<div class="history-row"><div><b>${a.marca}</b><span>${nf(a.vistasGeneradas||0)} vistas</span></div><strong>$${nf(a.pagoAcumulado||0)}</strong></div>`).join("")}</div>`:`<p class="muted">Todavía no cerraste una campaña por rendimiento.</p>`}</section>
 </div>`;
 c.querySelectorAll(".campaign-sign").forEach(btn=>btn.addEventListener("click",()=>{const r=gameState.firmarCampania(btn.dataset.id); if(!r.ok)alert(r.motivo); renderMonetizacion(c);})); return c;
}
export const monetizacionScreen={render:renderMonetizacion}; export default monetizacionScreen;
